name: ChaiBar
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  sign_in_with_apple: ^6.1.4
  flutter_timer_countdown: ^1.0.7
  permission_handler: ^11.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.1.4
  shared_preferences: ^2.2.3
  google_fonts: ^4.0.3
  json_annotation: ^4.5.0
  toastification: ^2.0.0
  email_validator: ^2.1.16
  shimmer: ^2.0.0
  path_provider: ^2.0.11
  path: ^1.8.2
  image: ^4.0.15
  screenshot: ^3.0.0
  flutter_image_compress: ^1.1.0
  local_auth: ^2.2.0
  carousel_slider: ^4.2.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^17.2.1
  share_plus: ^10.0.0
  connectivity_plus: ^6.0.3
  smooth_page_indicator: ^1.1.0
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_keyboard_visibility: ^6.0.0
  sqflite: ^2.3.3+1
  floor: ^1.5.0
  device_info_plus: ^10.1.1
  flutter_broadcasts: ^0.4.0
  fluttertoast: ^8.2.1
  google_sign_in: 6.2.1
  curved_navigation_bar: ^1.0.6
  flutter_dash: ^1.0.0
  flutter_svg: ^2.0.0
  flutter_credit_card: ^4.0.1
  bottom_navy_bar: ^6.0.0
  motion_tab_bar_v2: ^0.3.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.1
  flutter_cache_manager: ^3.3.1
  coupon_uikit: ^0.2.1
  get: ^4.7.2
  device_preview: ^1.2.0
  apple_pay_flutter: ^1.0.3
  mask_text_input_formatter: ^2.9.0
  package_info_plus: ^8.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/

  fonts:
    - family: CustomFont
      fonts:
        - asset: font/marlin_regular.otf
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
